Added comments, seperate phone number to use functions to check for positive integar only

diff --git a/AddCust b/AddCust
--- a/AddCust
+++ b/AddCust
@@ -7,6 +7,8 @@
 #Clears the screen content
 clear
 
+#This function asks user for customer email. The valid email function is called
+#after to check is whether email is valid
 function readEmail
 {
 	printf "\tPlease enter the customer email address: "
@@ -14,7 +16,9 @@ function readEmail
 	validEmail
 }
 
-#This function validates whether email entered is entered is valid or not
+#This function validates whether email entered is valid or not.
+#If email is not valid the readEmail function is called again to ask user to 
+#re-enter email address
 function validEmail
 {
 	validEmail=false
@@ -44,24 +48,47 @@ function validEmail
 # }
 
 
-#Asks user to enter email address. Need to error checking that email if unique
-#and take emails contains @ with a . 
 
+#This function asks user for phone number. The validPhoneNumber 
+#function is then called to check is phone number is integars only
+function readPhoneNumber
+{
+	printf "\n\tPlease enter the customer telephone Number: "
+	read phoneNumber
+	validNumber
+}
+
+#This function checks does phone number contain positive integars only.
+#If not, the readPhoneNumber function to called again to ask user to re-enter
+#phone number 
+function validNumber
+{
+	if ! [[ $phoneNumber =~ ^[0-9]+$ ]]; then
+		printf "\n\tInvalid (String) entry, only positive integers are allowed. Please re-renter option\n"
+		readPhoneNumber
+	fi
+}
+
+#Call readEmail function 
 readEmail
 
+#Asks user for name and take in as parameter - no error checking is done
 printf "\n\tPlease enter the customer name: "
 read name
 
+#Asks user for alias and take in as parameter - no error checking is done
 printf "\n\tPlease enter the customer alias: "
 read alias
 
+#Asks user for address and take in as parameter - no error checking is done
 printf "\n\tPlease enter the customer address: "
 read address
 
-printf "\n\tPlease enter the customer telephone Number: "
-read phoneNumber
+#Calls the readPhoneNumber function to ask user for number and take in as parameter 
+readPhoneNumber
 
 #Takes the entered parameters and list them in a file called CustomerDetails
 echo "$email		$name		$alias		$address		$phoneNumber" >> ../CustomerDetails
 printf "\n\tCustomer successfully added.\n\tPlease enter to return to main menu"
 read
+clear
