Added while loop for actionAfterSearch function

diff --git a/RemCust b/RemCust
--- a/RemCust
+++ b/RemCust
@@ -26,36 +26,54 @@ function checkInput
 	if [ -z $input ]; then
 		printf "\n\tNo entry detected. Please re-enter search term"
 		readInput
-	elif [[ $(grep -i $input ../CustomerDetails | wc -l) -ne 0 ]]; then
-		printf "\nOne or more matches were found:\n"
-		grep -i $input ../CustomerDetails 
-		printf "\n\t1) Remove all matching entries found\n"
-		printf "\n\t2) Perform another search\n"
-		printf "\nEnter choice: "
-			read choice
-			if [[ $choice -eq 1 ]]; then
-				removeInput
-			elif [[ $choice -eq 2 ]]; then
-				readInput
-			else
-				printf "\n\tInvalid string entered. Returning to main menu\n"
-			fi
-	elif [[ $(grep -i $input ../CustomerDetails | wc -l) -eq 0 ]]; then
-		printf "\n\tNo matches were found\n"
+	elif [[ $(grep -i $input CustomerDetails | wc -l) -ne 0 ]]; then
+		printf "\n$(grep -i -c $input CustomerDetails) match(s) were found:\n"
+		grep -i $input CustomerDetails 
+		# awk '{ if ($2 == "$input" ) print $0 }' ../CustomerDetails 
+		actionAfterSearch
+	elif [[ $(grep -i $input CustomerDetails | wc -l) -eq 0 ]]; then
+		printf "\nNo matches were found\n"
+		actionAfterSearch
 	fi
 }
 
-
+#This function removes the searched 
 function removeInput
 {
 	#Inverted search - All but the searched item is moved to an temp file
 	#Todo: Currently removes all customers if have same name with no validation
 	#Need to print out how many is found and ask do user want to remove all or redo search and remove 
-	grep -v $input ../CustomerDetails > /tmp/CustomerDetails
+	grep -v $input CustomerDetails > /tmp/CustomerDetails
 
 	#Temp file is moved back to the same directory replacing the old file
-	mv /tmp/CustomerDetails ../CustomerDetails
-	printf "\n\tCustomer Details successfully removed\n"
+	mv /tmp/CustomerDetails CustomerDetails
+	printf "\nCustomer Details successfully removed\n"
+}
+
+function actionAfterSearch
+{
+	validChoice=false;
+	while [[ $validChoice = false ]]; do
+		printf "\n\t1) Remove all matching entries found\n"
+		printf "\n\t2) Perform another search\n"
+		printf "\n\t=========================================\n"
+		printf "\n\t0) Return to Main Menu\n"
+		printf "\nEnter choice: "
+		read choice
+			if ! [[ $choice =~ ^-?[0-9]+$ ]]; then
+				printf "\nInvalid (String) entry, only integers shown are allowed. Please re-renter option\n"
+			elif [ $choice -le -1 ] || [ $choice -ge 3 ]; then
+				printf "\nInvalid number entered\n"
+			elif [[ $choice -eq 1 ]]; then
+				removeInput
+			elif [[ $choice -eq 2 ]]; then
+				readInput
+			else
+				validChoice=valid
+			fi
+	done
 }
 
 readInput
+
+# awk '{ if ($2 == "Kevin" ) print $0 }' ../CustomerDetails 
